export const bowlGames = [
    "68 Ventures Bowl",
    "Alamo Bowl",
    "Arizona Bowl",
    "Armed Forces Bowl",
    "Bahamas Bowl",
    "Birmingham Bowl",
    "Boca Raton Bowl",
    "Camellia Bowl",
    "Citrus Bowl",
    "Cotton Bowl",
    "Cure Bowl",
    "Detrot Bowl",
    "Duke's Mayo Bowl",
    "Famous Idaho Potato Bowl",
    "Fenway Bowl",
    "Fiesta Bowl",
    "First Responder Bowl",
    "Frisco Bowl",
    "Gasparilla Bowl",
    "Gator Bowl",
    "Guaranteed Rate Bowl",
    "Hawaiʻi Bowl",
    "Holiday Bowl",
    "Independence Bowl",
    "LA Bowl",
    "Las Vegas Bowl",
    "Liberty Bowl",
    "Military Bowl",
    "Music City Bowl",
    "Myrtle Beach Bowl",
    "New Mexico Bowl",
    "New Orleans Bowl",
    "Orange Bowl",
    "Peach Bowl",
    "Pinstripe Bowl",
    "Pop-Tarts Bowl",
    "ReliaQuest Bowl",
    "Rose Bowl",
    "Sugar Bowl",
    "Sun Bowl",
    "Texas Bowl",
]